### PR TITLE
Distill template v2

### LINKED ISSUE #6: Find a solution for menu/navigation

### PR DESCRIPTION
**Pull request by plonerma**
Pretty much done applying all the changes necessary to use distill template v2. Note that all tags starting with `dt-` now start with `d-`.

The references can no be kept in a sperate file (always make sure there are no additional curled braces in the title, distill cannot deal with those). The now is also much less eye catching.

### CODE REVIEW

**Review by luis-mueller — COMMENTED** [review]
The whole layout is way clearer and the toc on the side is a nice solution to our menu problem.
I will adjust a few things regarding the flow of between the pages and then we can merge this.

Looks good!

**Comment by plonerma** [comment]
Yes I agree - though I liked the other font more ;)
Perfect, then we can show the new version tomorrow :)

**Comment by luis-mueller** [comment]
Yeah, I will let you have one final look at my changes once I am done and then you can merge!

**Comment by luis-mueller** [comment]
Alright im done! Feel free to read over and then merge once you feel ready.

**Pull request merged**
